language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  # Python 3.x not supported yet
#  - "3.5"
#  - "3.6"
install:
  - pip install numpy cython
  - pip install mdtraj
  - pip install nose
  - pip install -e .

script:
  # Your test script goes here
  - nosetests -v
